//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntraWeb.Resources.Email {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal EmailResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntraWeb.Resources.Email.EmailResources", typeof(EmailResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title&gt;{title}&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            padding-top: 0 !important;
        ///            padding-bottom: 0 !important;
        ///            margin: 0 !important;
        ///            width: 100% !important;
        ///            -webkit-text-size-adjust: 100% !important;
        ///            -ms-text-size-adjust: 100% !important;
        ///            -webkit-font-smoothing: antialiased !important;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;p&gt;
        ///    Heslo si môžete obnoviť na nasledujúcom odkaze: &lt;a href=&quot;http://www.example.com&quot;&gt;www.example.com&lt;/a&gt;.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;p&gt;
        ///    &lt;a href=&quot;http://example.com&quot;&gt;Lorem ipsum&lt;/a&gt; dolor sit amet,
        ///    consectetur adipiscing elit. Integer sit amet euismod enim,
        ///    ac viverra odio. Donec finibus erat tortor, viverra imperdiet
        ///    nibh iaculis at. Nullam porttitor sagittis turpis, vel
        ///    imperdiet magna malesuada vel. Duis id erat nulla. Integer
        ///    consectetur tincidunt tortor sit amet sagittis. Integer
        ///    vestibulum sapien id blandit fermentum. Curabitur nec ligula
        ///    convallis, gravida velit non, blandit dui. Proin fauci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
